import { ActionType } from '../../enums/action-type';
import { FileStatus } from '../../enums/file-status';
import { TextType } from '../../enums/text-type';
import { Lesson } from '../../models/lesson';
import { lines } from '../lines';

export const lesson08: Lesson = {
    id: 'merging',
    number: 8,
    title: 'Merging',
    minutes: 5,
    summary: 'How to bring a finished idea back into main.',
    topics: [
        {
            term: 'Merge',
            plain: 'Combine branches',
            definition: 'Bring the changes from one branch into another.',
        },
    ],
    workspace: {
        config: { showStaging: true, showOrigin: true },
        files: [
            {
                name: 'pancakes',
                content: lines(
                    'Pancakes',
                    '1 egg',
                    '1 cup flour',
                    '1 cup milk',
                    '1 pinch of salt',
                    '1 handful of blueberries',
                    '1 spoon of maple syrup',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'groceries',
                content: lines('eggs', 'flour', 'butter', 'milk'),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'cookies',
                content: lines(
                    'Cookies',
                    '2 cups flour',
                    '1 cup butter',
                    '1 cup sugar',
                    '1 cup of chocolate chips',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'soup',
                content: lines(
                    'Soup',
                    '3 potatoes',
                    '1 onion',
                    '4 cups of water',
                    '1 handful of croutons',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'notes',
                content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                modifiedOn: '2026-10-02',
                status: FileStatus.New,
                staged: false,
            },
        ],
        history: [
            {
                id: '9',
                message: 'Swap the egg for a banana',
                author: 'You',
                when: 'earlier',
                branch: 'vegan',
            },
            {
                id: '8',
                message: 'Fix potato spelling',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: 'sam2', message: 'Add croutons', author: 'Sam', when: 'earlier', branch: 'main' },
            {
                id: 'sam1',
                message: 'Add soup recipe',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '7',
                message: 'Add chocolate chips',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '6',
                message: 'Undo Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '5',
                message: 'Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '4', message: 'Add maple syrup', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: '3',
                message: 'Add cookie recipe',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '2',
                message: 'Add blueberries and milk',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '1',
                message: 'Start of the recipe book',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
        ],
        branch: 'main',
        branches: ['main', 'vegan'],
        origin: {
            label: 'Origin',
            files: [
                {
                    name: 'pancakes',
                    content: lines(
                        'Pancakes',
                        '1 egg',
                        '1 cup flour',
                        '1 cup milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        'Serves 4',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'groceries',
                    content: lines('eggs', 'flour', 'butter', 'milk'),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'cookies',
                    content: lines(
                        'Cookies',
                        '2 cups flour',
                        '1 cup butter',
                        '1 cup sugar',
                        '1 cup of chocolate chips',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'soup',
                    content: lines(
                        'Soup',
                        '3 potatoes',
                        '1 onion',
                        '4 cups of water',
                        '1 handful of croutons',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
            ],
            history: [
                {
                    id: 'sam3',
                    message: 'Add serving size',
                    author: 'Sam',
                    when: 'this morning',
                    branch: 'main',
                },
                {
                    id: '9',
                    message: 'Swap the egg for a banana',
                    author: 'You',
                    when: 'earlier',
                    branch: 'vegan',
                },
                {
                    id: '8',
                    message: 'Fix potato spelling',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam2',
                    message: 'Add croutons',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam1',
                    message: 'Add soup recipe',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '7',
                    message: 'Add chocolate chips',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '6',
                    message: 'Undo Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '5',
                    message: 'Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '4',
                    message: 'Add maple syrup',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '3',
                    message: 'Add cookie recipe',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '2',
                    message: 'Add blueberries and milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '1',
                    message: 'Start of the recipe book',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
            ],
            pullRequests: [],
        },
        upstream: null,
    },
    recap: "You tried an idea on its own branch, kept main up to date, and merged the result back. Git did the combining for you. In the next lesson, it can't.",
    steps: [
        {
            id: '8.1',
            title: 'Main moved on',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'While you were busy with bananas, Sam added a serving size to main. Grab it before you do anything else.',
                },
                {
                    type: TextType.Details,
                    text: 'On a real team, branches drift apart all the time. Merging brings them back together.',
                },
            ],
            task: 'Press Pull.',
            done: "main has Sam's serving size, and vegan has your banana. The two lines have drifted apart, which is completely normal.",
            // Check. main has a snapshot that vegan doesn't have.
            actions: [
                {
                    type: ActionType.Pull,
                    files: [
                        {
                            name: 'pancakes',
                            content: lines(
                                'Pancakes',
                                '1 egg',
                                '1 cup flour',
                                '1 cup milk',
                                '1 pinch of salt',
                                '1 handful of blueberries',
                                '1 spoon of maple syrup',
                                'Serves 4',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'groceries',
                            content: lines('eggs', 'flour', 'butter', 'milk'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'cookies',
                            content: lines(
                                'Cookies',
                                '2 cups flour',
                                '1 cup butter',
                                '1 cup sugar',
                                '1 cup of chocolate chips',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'soup',
                            content: lines(
                                'Soup',
                                '3 potatoes',
                                '1 onion',
                                '4 cups of water',
                                '1 handful of croutons',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'notes',
                            content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.New,
                            staged: false,
                        },
                    ],
                },
            ],
        },
        {
            id: '8.2',
            title: 'Merge',
            body: [
                {
                    type: TextType.Paragraph,
                    text: "Merging brings vegan's snapshots into main. Git looks at both lines and combines the changes for you.",
                },
                {
                    type: TextType.Details,
                    text: "The command is git merge. A merge snapshot has two parents, one from each line. Git merges on its own whenever the changes don't touch the same lines.",
                },
                {
                    type: TextType.Paragraph,
                    text: "You always merge into the branch you're on, so stay on main.",
                },
            ],
            task: 'Press Merge and pick vegan.',
            done: 'A merge snapshot joins the two lines. The pancakes file now has the banana and the serving size. Git combined them on its own, because they changed different lines.',
            // Check. A merge snapshot joins the two lines, and pancakes has the banana and the serving size.
            actions: [
                {
                    type: ActionType.Merge,
                    branch: 'vegan',
                    message: 'Merge vegan into main',
                    files: [
                        {
                            name: 'pancakes',
                            content: lines(
                                'Pancakes',
                                '1 mashed banana',
                                '1 cup flour',
                                '1 cup milk',
                                '1 pinch of salt',
                                '1 handful of blueberries',
                                '1 spoon of maple syrup',
                                'Serves 4',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'groceries',
                            content: lines('eggs', 'flour', 'butter', 'milk'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'cookies',
                            content: lines(
                                'Cookies',
                                '2 cups flour',
                                '1 cup butter',
                                '1 cup sugar',
                                '1 cup of chocolate chips',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'soup',
                            content: lines(
                                'Soup',
                                '3 potatoes',
                                '1 onion',
                                '4 cups of water',
                                '1 handful of croutons',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'notes',
                            content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.New,
                            staged: false,
                        },
                    ],
                },
            ],
        },
        {
            id: '8.3',
            title: 'Clean up',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'The vegan branch did its job. Deleting it only removes the name. Its snapshots are part of main now, so nothing gets lost.',
                },
                {
                    type: TextType.Details,
                    text: "This only deletes your own vegan. The copy on origin stays until you delete it there too. Git also won't delete a branch you haven't merged unless you force it.",
                },
            ],
            task: 'Press Delete branch on vegan.',
            done: "vegan is gone from the list, and its banana snapshot is still in main's history. Teams delete finished branches all the time to keep the list short.",
            // Check. The vegan branch is gone, and its snapshots are still in main.
            actions: [{ type: ActionType.DeleteBranch, branch: 'vegan' }],
        },
        {
            id: '8.4',
            title: 'Share it',
            body: [
                {
                    type: TextType.Paragraph,
                    text: "main changed in your local history. Origin doesn't know yet.",
                },
                {
                    type: TextType.Details,
                    text: 'Pushing a merge snapshot works like pushing any other. Origin shows both lines joining back together.',
                },
            ],
            task: 'Press Push.',
            done: 'Origin main has the vegan pancakes. Tomorrow morning, Sam pulls and finds bananas at breakfast.',
            // Check. Origin main has the merge snapshot.
            actions: [{ type: ActionType.Push }],
        },
    ],
};
