import { FileStatus } from '../../enums/file-status';
import { FileType } from '../../enums/file-type';
import { TextType } from '../../enums/text-type';
import { Lesson } from '../../models/lesson';
import { doc } from '../doc';

export const lesson09: Lesson = {
    id: 'when-changes-collide',
    number: 9,
    title: 'When changes collide',
    minutes: 6,
    summary: 'What happens when you and a teammate change the same line, and how you decide.',
    topics: [
        {
            term: 'Conflict',
            plain: 'Changes that collide',
            definition:
                'Two people changed the same line, and Git needs you to choose which version stays.',
        },
    ],
    workspace: {
        config: { showStaging: true, showOrigin: true },
        files: [
            {
                name: 'pancakes',
                content: doc(
                    'Pancakes',
                    '1 mashed banana',
                    '1 cup flour',
                    '1 cup milk',
                    '1 pinch of salt',
                    '1 handful of blueberries',
                    '1 spoon of maple syrup',
                    'Serves 4',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'groceries',
                content: 'eggs\nflour\nbutter\nmilk\n',
                type: FileType.Txt,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'cookies',
                content: doc(
                    'Cookies',
                    '2 cups flour',
                    '1 cup butter',
                    '1 cup sugar',
                    '1 cup of chocolate chips',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'soup',
                content: doc(
                    'Soup',
                    '3 potatoes',
                    '1 onion',
                    '4 cups of water',
                    '1 handful of croutons',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'notes',
                content: 'The pancakes are from a box mix.\nBuy more box mix.\n',
                type: FileType.Txt,
                modifiedOn: '2026-10-02',
                status: FileStatus.New,
                staged: false,
            },
        ],
        history: [
            {
                id: '10',
                message: 'Merge vegan into main',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: 'sam3',
                message: 'Add serving size',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '9',
                message: 'Swap the egg for a banana',
                author: 'You',
                when: 'earlier',
                branch: 'vegan',
            },
            {
                id: '8',
                message: 'Fix potato spelling',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: 'sam2', message: 'Add croutons', author: 'Sam', when: 'earlier', branch: 'main' },
            {
                id: 'sam1',
                message: 'Add soup recipe',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '7',
                message: 'Add chocolate chips',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '6',
                message: 'Undo Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '5',
                message: 'Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '4', message: 'Add maple syrup', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: '3',
                message: 'Add cookie recipe',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '2',
                message: 'Add blueberries and milk',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '1',
                message: 'Start of the recipe book',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
        ],
        branch: 'main',
        branches: ['main'],
        origin: {
            label: 'Origin',
            files: [
                {
                    name: 'pancakes',
                    content: doc(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup almond milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        'Serves 4',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'groceries',
                    content: 'eggs\nflour\nbutter\nmilk\n',
                    type: FileType.Txt,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'cookies',
                    content: doc(
                        'Cookies',
                        '2 cups flour',
                        '1 cup butter',
                        '1 cup sugar',
                        '1 cup of chocolate chips',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'soup',
                    content: doc(
                        'Soup',
                        '3 potatoes',
                        '1 onion',
                        '4 cups of water',
                        '1 handful of croutons',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
            ],
            history: [
                {
                    id: 'sam4',
                    message: 'Use almond milk',
                    author: 'Sam',
                    when: 'an hour ago',
                    branch: 'main',
                },
                {
                    id: '10',
                    message: 'Merge vegan into main',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam3',
                    message: 'Add serving size',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '9',
                    message: 'Swap the egg for a banana',
                    author: 'You',
                    when: 'earlier',
                    branch: 'vegan',
                },
                {
                    id: '8',
                    message: 'Fix potato spelling',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam2',
                    message: 'Add croutons',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam1',
                    message: 'Add soup recipe',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '7',
                    message: 'Add chocolate chips',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '6',
                    message: 'Undo Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '5',
                    message: 'Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '4',
                    message: 'Add maple syrup',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '3',
                    message: 'Add cookie recipe',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '2',
                    message: 'Add blueberries and milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '1',
                    message: 'Start of the recipe book',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
            ],
            pullRequests: [],
        },
        upstream: null,
    },
    recap: "You and Sam changed the same line, so Git stopped and asked you to choose. You picked an answer, saved it, and shared it. A conflict looks scary, but it's only Git asking you a question.",
    steps: [
        {
            id: '9.1',
            title: 'Same line, two answers',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'Your vegan pancakes still call for regular milk, and that comes from cows. Not very vegan. Switch it to oat milk.',
                },
                {
                    type: TextType.Details,
                    text: "Commit never talks to origin. It only looks at your own history, so it can't know what anyone else did since your last pull.",
                },
            ],
            task: 'Press Edit to change the milk to oat milk in pancakes.md, then stage it and commit.',
            done: "Your fix is saved. Here's what you don't know yet. Sam fixed the same line an hour ago, with almond milk, and already pushed it.",
            // Check. Your oat milk snapshot is in local history.
            actions: [
                {
                    type: 'edit',
                    file: 'pancakes',
                    content: doc(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup oat milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        'Serves 4',
                    ),
                },
                { type: 'stage', file: 'pancakes' },
                { type: 'commit', message: 'Use oat milk' },
            ],
        },
        {
            id: '9.2',
            title: 'Pull',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'You know the rule by now. Pull before you push.',
                },
                {
                    type: TextType.Details,
                    text: 'Git only gets stuck when two snapshots change the same lines. Inside the file, it marks your version and theirs with rows of <<<<<<<, =======, and >>>>>>>.',
                },
            ],
            task: 'Press Pull.',
            done: "Git stopped and marked pancakes.md as Conflict. You and Sam both changed the milk line, and Git won't guess which one should win.",
            // Check. pancakes.md shows Conflict.
            // Workspace. pancakes.md shows both versions of the milk line, yours and Sam's, one above the other.
            actions: [
                {
                    type: 'pull',
                    files: [
                        {
                            name: 'pancakes',
                            content: doc(
                                'Pancakes',
                                '1 mashed banana',
                                '1 cup flour',
                                'Yours. 1 cup oat milk',
                                "Sam's. 1 cup almond milk",
                                '1 pinch of salt',
                                '1 handful of blueberries',
                                '1 spoon of maple syrup',
                                'Serves 4',
                            ),
                            type: FileType.Doc,
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Conflict,
                            staged: false,
                        },
                        {
                            name: 'groceries',
                            content: 'eggs\nflour\nbutter\nmilk\n',
                            type: FileType.Txt,
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'cookies',
                            content: doc(
                                'Cookies',
                                '2 cups flour',
                                '1 cup butter',
                                '1 cup sugar',
                                '1 cup of chocolate chips',
                            ),
                            type: FileType.Doc,
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'soup',
                            content: doc(
                                'Soup',
                                '3 potatoes',
                                '1 onion',
                                '4 cups of water',
                                '1 handful of croutons',
                            ),
                            type: FileType.Doc,
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'notes',
                            content: 'The pancakes are from a box mix.\nBuy more box mix.\n',
                            type: FileType.Txt,
                            modifiedOn: '2026-10-02',
                            status: FileStatus.New,
                            staged: false,
                        },
                    ],
                },
            ],
        },
        {
            id: '9.3',
            title: 'Pick an answer',
            body: [
                {
                    type: TextType.Paragraph,
                    text: "Welcome to the milk wars. Git shows you both lines. Keep yours, keep Sam's, or write a new one.",
                },
                {
                    type: TextType.Paragraph,
                    text: 'Any answer works. Git just needs you to pick one.',
                },
                {
                    type: TextType.Details,
                    text: 'In real Git you open the file, delete the markers, keep the lines you want, and run git add to mark it fixed. Many editors add buttons like Accept current and Accept incoming to make this faster.',
                },
            ],
            task: 'Press Resolve on pancakes.md and pick the line you want.',
            done: "pancakes.md has one milk line again, and Resolve staged it for you. Whatever you picked, you picked it on purpose. That's the whole point of a conflict.",
            // Check. pancakes.md no longer shows Conflict, and it's staged.
            actions: [
                {
                    type: 'resolve',
                    file: 'pancakes',
                    content: doc(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup oat milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        'Serves 4',
                    ),
                },
            ],
        },
        {
            id: '9.4',
            title: 'Finish up',
            body: [
                {
                    type: TextType.Paragraph,
                    text: "Your answer is staged, but it isn't saved yet. Commit it, then push it so Sam finds out who won the milk wars.",
                },
                {
                    type: TextType.Details,
                    text: "Fixing a conflict ends with a merge commit, like any other merge. git log shows your snapshot, Sam's, and the merge that joined them.",
                },
            ],
            task: 'Press Commit, then press Push.',
            done: "Origin has your answer. History shows your milk, Sam's milk, and the one you kept, so nobody has to argue about it twice.",
            // Check. Origin has the snapshot with your answer.
            actions: [{ type: 'commit', message: 'Settle the milk wars' }, { type: 'push' }],
        },
    ],
};
