import { FileStatus } from '../../enums/file-status';
import { FileType } from '../../enums/file-type';
import { TextType } from '../../enums/text-type';
import { Lesson } from '../../models/lesson';
import { doc } from '../doc';

export const lesson12: Lesson = {
    id: 'good-habits',
    number: 12,
    title: 'Good habits',
    minutes: 5,
    summary: 'How to keep private files out and mark the versions that matter.',
    topics: [
        {
            term: 'Ignore',
            plain: 'Keep out of Git',
            definition: 'Tell Git to never track a file, like private notes or passwords.',
        },
        {
            term: 'Tag',
            plain: 'A named version',
            definition: 'A label on one snapshot, like Summer edition, so you find it again later.',
        },
        {
            term: 'Release',
            plain: 'A finished version to share',
            definition:
                'A tagged version you publish on GitHub so others download that exact copy.',
        },
    ],
    workspace: {
        config: { showStaging: true, showOrigin: true },
        files: [
            {
                name: 'pancakes',
                content: doc(
                    'Pancakes',
                    '1 mashed banana',
                    '1 cup flour',
                    '1 cup oat milk',
                    '1 pinch of salt',
                    '1 handful of blueberries',
                    '1 spoon of maple syrup',
                    '1 cup of chocolate chips',
                    'Serves 4',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'groceries',
                content: 'eggs\nflour\nbutter\nmilk\n',
                type: FileType.Txt,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'cookies',
                content: doc(
                    'Cookies',
                    '2 cups flour',
                    '1 cup butter',
                    '1 cup sugar',
                    '1 cup of chocolate chips',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'soup',
                content: doc(
                    'Soup',
                    '3 potatoes',
                    '1 onion',
                    '4 cups of water',
                    '1 handful of croutons',
                ),
                type: FileType.Doc,
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'notes',
                content: 'The pancakes are from a box mix.\nBuy more box mix.\n',
                type: FileType.Txt,
                modifiedOn: '2026-10-02',
                status: FileStatus.New,
                staged: false,
            },
        ],
        history: [
            {
                id: '15',
                message: 'Merge chocolate into main',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '14',
                message: 'Use 1 cup of chocolate chips',
                author: 'You',
                when: 'earlier',
                branch: 'chocolate',
            },
            {
                id: '13',
                message: 'Add chocolate chips to pancakes',
                author: 'You',
                when: 'earlier',
                branch: 'chocolate',
            },
            {
                id: '12',
                message: 'Settle the milk wars',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '11', message: 'Use oat milk', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: 'sam4',
                message: 'Use almond milk',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '10',
                message: 'Merge vegan into main',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: 'sam3',
                message: 'Add serving size',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '9',
                message: 'Swap the egg for a banana',
                author: 'You',
                when: 'earlier',
                branch: 'vegan',
            },
            {
                id: '8',
                message: 'Fix potato spelling',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: 'sam2', message: 'Add croutons', author: 'Sam', when: 'earlier', branch: 'main' },
            {
                id: 'sam1',
                message: 'Add soup recipe',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '7',
                message: 'Add chocolate chips',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '6',
                message: 'Undo Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '5',
                message: 'Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '4', message: 'Add maple syrup', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: '3',
                message: 'Add cookie recipe',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '2',
                message: 'Add blueberries and milk',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '1',
                message: 'Start of the recipe book',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
        ],
        branch: 'main',
        branches: ['main'],
        origin: {
            label: 'Origin',
            files: [
                {
                    name: 'pancakes',
                    content: doc(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup oat milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        '1 cup of chocolate chips',
                        'Serves 4',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'groceries',
                    content: 'eggs\nflour\nbutter\nmilk\n',
                    type: FileType.Txt,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'cookies',
                    content: doc(
                        'Cookies',
                        '2 cups flour',
                        '1 cup butter',
                        '1 cup sugar',
                        '1 cup of chocolate chips',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'soup',
                    content: doc(
                        'Soup',
                        '3 potatoes',
                        '1 onion',
                        '4 cups of water',
                        '1 handful of croutons',
                    ),
                    type: FileType.Doc,
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
            ],
            history: [
                {
                    id: '15',
                    message: 'Merge chocolate into main',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '14',
                    message: 'Use 1 cup of chocolate chips',
                    author: 'You',
                    when: 'earlier',
                    branch: 'chocolate',
                },
                {
                    id: '13',
                    message: 'Add chocolate chips to pancakes',
                    author: 'You',
                    when: 'earlier',
                    branch: 'chocolate',
                },
                {
                    id: '12',
                    message: 'Settle the milk wars',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '11',
                    message: 'Use oat milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam4',
                    message: 'Use almond milk',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '10',
                    message: 'Merge vegan into main',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam3',
                    message: 'Add serving size',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '9',
                    message: 'Swap the egg for a banana',
                    author: 'You',
                    when: 'earlier',
                    branch: 'vegan',
                },
                {
                    id: '8',
                    message: 'Fix potato spelling',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam2',
                    message: 'Add croutons',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam1',
                    message: 'Add soup recipe',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '7',
                    message: 'Add chocolate chips',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '6',
                    message: 'Undo Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '5',
                    message: 'Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '4',
                    message: 'Add maple syrup',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '3',
                    message: 'Add cookie recipe',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '2',
                    message: 'Add blueberries and milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '1',
                    message: 'Start of the recipe book',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
            ],
            pullRequests: [],
        },
        upstream: null,
    },
    recap: "You hid a secret, marked a version, and shared it. That's the whole course. You know what a repository, a snapshot, a branch, and origin are, and you can work with other people without wrecking each other's changes.",
    steps: [
        {
            id: '12.1',
            title: 'Keep notes private',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'Back to the recipe book, where notes.txt still holds the box mix secret. One wrong click and the whole family finds out.',
                },
                {
                    type: TextType.Paragraph,
                    text: "Ignore tells Git to act like a file isn't there. The file stays in your working files, but it never goes in a snapshot.",
                },
                {
                    type: TextType.Details,
                    text: 'Git keeps the list of ignored files in a file called .gitignore. Teams use it for passwords, personal settings, and the junk files that apps leave behind.',
                },
            ],
            task: 'Press Ignore on notes.txt.',
            done: "notes.txt turned grey, and Stage won't work on it anymore. The box mix secret is safe for good.",
            // Check. notes.txt shows Ignored and can't be staged.
            actions: [{ type: 'ignore', file: 'notes' }],
        },
        {
            id: '12.2',
            title: 'Mark a version',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'The recipe book is ready for the whole family. Put a name on this moment so you can find it again a year from now.',
                },
                {
                    type: TextType.Details,
                    text: 'The command is git tag. Software teams tag every version they release, like v1.0 and v2.0, so they can always find the code they shipped.',
                },
            ],
            task: 'Click your latest snapshot, press New tag, and name it Summer edition.',
            done: 'Summer edition sits on your latest snapshot. A branch moves forward every time you commit, but a tag never moves.',
            // Check. The Summer edition tag shows on your latest snapshot.
            actions: [{ type: 'newTag', name: 'Summer edition' }],
        },
        {
            id: '12.3',
            title: 'Publish it',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'The tag only lives in your local history so far. Push it to origin, and GitHub lets you turn it into a release anyone can download.',
                },
                {
                    type: TextType.Details,
                    text: 'Real Git only pushes tags when you ask, with git push and the tags option. A release is a GitHub page built on a tag, with notes and downloads attached.',
                },
            ],
            task: 'Press Push.',
            done: 'Origin shows a Summer edition release. Your family can grab this version of the recipe book, even after you add 40 more recipes.',
            // Check. Origin shows a Summer edition release.
            actions: [{ type: 'push' }],
        },
        {
            id: '12.4',
            title: 'Recap',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'You learned a lot of new words in this course. Time to see how many of them stuck.',
                },
                {
                    type: TextType.Details,
                    text: 'The glossary lists every Git word from the course with its plain meaning. Keep it open the first few times you use Git for real.',
                },
            ],
            task: 'Click each Git word, then click what it means in plain words.',
            done: "All 8 match. You can now explain Git to a friend. Honestly, that's more than a lot of people who use Git every day can do.",
            // Check. All 8 pairs match. The words are repository, commit, stage, push, pull, branch, merge, and pull request.
            actions: [{ type: 'matchWords' }],
        },
    ],
};
