import { ActionType } from '../../enums/action-type';
import { FileStatus } from '../../enums/file-status';
import { TextType } from '../../enums/text-type';
import { WorkspaceEventType } from '../../enums/workspace-event-type';
import { Lesson } from '../../models/lesson';
import { lines } from '../lines';

export const lesson10: Lesson = {
    id: 'asking-before-merging',
    number: 10,
    title: 'Asking before merging',
    minutes: 6,
    summary: 'How to suggest a change and get it checked before it lands on main.',
    topics: [
        {
            term: 'Pull request',
            plain: 'A request to merge',
            definition: 'On GitHub, a proposal to merge your branch so others review it first.',
        },
        {
            term: 'Review',
            plain: 'A second pair of eyes',
            definition:
                'Someone reads your pull request, leaves comments, and approves it before it merges.',
        },
    ],
    workspace: {
        config: { showStaging: true, showOrigin: true },
        files: [
            {
                name: 'pancakes',
                content: lines(
                    'Pancakes',
                    '1 mashed banana',
                    '1 cup flour',
                    '1 cup oat milk',
                    '1 pinch of salt',
                    '1 handful of blueberries',
                    '1 spoon of maple syrup',
                    '2 cups of chocolate chips',
                    'Serves 4',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'groceries',
                content: lines('eggs', 'flour', 'butter', 'milk'),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'cookies',
                content: lines(
                    'Cookies',
                    '2 cups flour',
                    '1 cup butter',
                    '1 cup sugar',
                    '1 cup of chocolate chips',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'soup',
                content: lines(
                    'Soup',
                    '3 potatoes',
                    '1 onion',
                    '4 cups of water',
                    '1 handful of croutons',
                ),
                modifiedOn: '2026-10-02',
                status: FileStatus.Unchanged,
                staged: false,
            },
            {
                name: 'notes',
                content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                modifiedOn: '2026-10-02',
                status: FileStatus.New,
                staged: false,
            },
        ],
        history: [
            {
                id: '13',
                message: 'Add chocolate chips to pancakes',
                author: 'You',
                when: 'earlier',
                branch: 'chocolate',
            },
            {
                id: '12',
                message: 'Settle the milk wars',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '11', message: 'Use oat milk', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: 'sam4',
                message: 'Use almond milk',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '10',
                message: 'Merge vegan into main',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: 'sam3',
                message: 'Add serving size',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '9',
                message: 'Swap the egg for a banana',
                author: 'You',
                when: 'earlier',
                branch: 'vegan',
            },
            {
                id: '8',
                message: 'Fix potato spelling',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: 'sam2', message: 'Add croutons', author: 'Sam', when: 'earlier', branch: 'main' },
            {
                id: 'sam1',
                message: 'Add soup recipe',
                author: 'Sam',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '7',
                message: 'Add chocolate chips',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '6',
                message: 'Undo Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '5',
                message: 'Add 10 cups of salt',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            { id: '4', message: 'Add maple syrup', author: 'You', when: 'earlier', branch: 'main' },
            {
                id: '3',
                message: 'Add cookie recipe',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '2',
                message: 'Add blueberries and milk',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
            {
                id: '1',
                message: 'Start of the recipe book',
                author: 'You',
                when: 'earlier',
                branch: 'main',
            },
        ],
        branch: 'chocolate',
        branches: ['main', 'chocolate'],
        origin: {
            label: 'Origin',
            files: [
                {
                    name: 'pancakes',
                    content: lines(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup oat milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        '2 cups of chocolate chips',
                        'Serves 4',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'groceries',
                    content: lines('eggs', 'flour', 'butter', 'milk'),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'cookies',
                    content: lines(
                        'Cookies',
                        '2 cups flour',
                        '1 cup butter',
                        '1 cup sugar',
                        '1 cup of chocolate chips',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
                {
                    name: 'soup',
                    content: lines(
                        'Soup',
                        '3 potatoes',
                        '1 onion',
                        '4 cups of water',
                        '1 handful of croutons',
                    ),
                    modifiedOn: '2026-10-02',
                    status: FileStatus.Unchanged,
                    staged: false,
                },
            ],
            history: [
                {
                    id: '13',
                    message: 'Add chocolate chips to pancakes',
                    author: 'You',
                    when: 'earlier',
                    branch: 'chocolate',
                },
                {
                    id: '12',
                    message: 'Settle the milk wars',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '11',
                    message: 'Use oat milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam4',
                    message: 'Use almond milk',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '10',
                    message: 'Merge vegan into main',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam3',
                    message: 'Add serving size',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '9',
                    message: 'Swap the egg for a banana',
                    author: 'You',
                    when: 'earlier',
                    branch: 'vegan',
                },
                {
                    id: '8',
                    message: 'Fix potato spelling',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam2',
                    message: 'Add croutons',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: 'sam1',
                    message: 'Add soup recipe',
                    author: 'Sam',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '7',
                    message: 'Add chocolate chips',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '6',
                    message: 'Undo Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '5',
                    message: 'Add 10 cups of salt',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '4',
                    message: 'Add maple syrup',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '3',
                    message: 'Add cookie recipe',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '2',
                    message: 'Add blueberries and milk',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
                {
                    id: '1',
                    message: 'Start of the recipe book',
                    author: 'You',
                    when: 'earlier',
                    branch: 'main',
                },
            ],
            pullRequests: [],
        },
        upstream: null,
    },
    recap: "You suggested a change, got feedback, fixed it, and merged it with Sam's blessing. A pull request turns a merge into a conversation.",
    steps: [
        {
            id: '10.1',
            title: 'Open a pull request',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'You made a chocolate branch and added chips to the vegan pancakes. Bold.',
                },
                {
                    type: TextType.Paragraph,
                    text: "Last time you merged bananas into Sam's breakfast without asking anyone. A pull request asks first. It gives everyone a place to look at your change and talk about it before it goes into main.",
                },
                {
                    type: TextType.Details,
                    text: "Pull request is GitHub's name for it. GitLab calls the same thing a merge request. The name sounds backwards, but you're asking the project to pull your branch in.",
                },
            ],
            task: 'Press New pull request and pick chocolate into main.',
            done: "Your request is open on origin, and Sam gets a notice. main hasn't changed. Nothing gets merged until someone says yes.",
            // Check. A pull request from chocolate into main is open on origin.
            // Workspace. The Pull requests tab on origin lists your request. Once the step is done, Sam's comment shows up on it.
            actions: [{ type: ActionType.NewPullRequest, from: 'chocolate', into: 'main' }],
            events: [
                {
                    type: WorkspaceEventType.Comment,
                    author: 'Sam',
                    text: 'Love it. But 2 cups of chips is a lot, even for me. Make it 1?',
                },
            ],
        },
        {
            id: '10.2',
            title: 'Answer the review',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'Sam left a comment. "Love it. But 2 cups of chips is a lot, even for me. Make it 1?"',
                },
                { type: TextType.Paragraph, text: 'Fair point. Make the change on your branch.' },
                {
                    type: TextType.Details,
                    text: 'Reviews are normal, even for tiny changes. A second pair of eyes catches mistakes, and the whole team learns what changed.',
                },
            ],
            task: 'Press Edit to change the chips to 1 cup in the pancakes file, then stage it and commit.',
            done: "The fix is saved, but the pull request still shows 2 cups. Sam only sees what's on origin.",
            // Check. A new snapshot on chocolate is in local history.
            actions: [
                {
                    type: ActionType.Edit,
                    file: 'pancakes',
                    content: lines(
                        'Pancakes',
                        '1 mashed banana',
                        '1 cup flour',
                        '1 cup oat milk',
                        '1 pinch of salt',
                        '1 handful of blueberries',
                        '1 spoon of maple syrup',
                        '1 cup of chocolate chips',
                        'Serves 4',
                    ),
                },
                { type: ActionType.Stage, file: 'pancakes' },
                { type: ActionType.Commit, message: 'Use 1 cup of chocolate chips' },
            ],
        },
        {
            id: '10.3',
            title: 'Update the request',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'A pull request follows its branch. Push to chocolate, and the request updates by itself.',
                },
                {
                    type: TextType.Details,
                    text: 'A review can go back and forth many times. Every push adds to the same request, so the whole conversation stays in one place.',
                },
            ],
            task: 'Press Push.',
            done: "The pull request shows your new snapshot right under Sam's comment. Sam can see you listened.",
            // Check. The pull request shows your new snapshot.
            // Workspace. Once the step is done, Sam approves the pull request.
            actions: [{ type: ActionType.Push }],
            events: [
                { type: WorkspaceEventType.Approve, author: 'Sam', text: 'Delicious. Ship it.' },
            ],
        },
        {
            id: '10.4',
            title: 'Merge it',
            body: [
                {
                    type: TextType.Paragraph,
                    text: 'Sam approved it with three words. "Delicious. Ship it." Now you can merge.',
                },
                {
                    type: TextType.Details,
                    text: "Many teams won't let anyone press Merge until someone approves. GitHub calls that a branch protection rule.",
                },
            ],
            task: 'Press Merge pull request.',
            done: 'Main on origin has the chocolate chips. The request closes, but it keeps the whole conversation, so anyone can see why main changed.',
            // Check. Origin main has the chocolate change, and the pull request is closed.
            actions: [{ type: ActionType.MergePullRequest }],
        },
        {
            id: '10.5',
            title: 'Catch up',
            body: [
                {
                    type: TextType.Paragraph,
                    text: "The merge happened on origin, so your own main doesn't have the chips yet. Go back to main and catch up.",
                },
                {
                    type: TextType.Details,
                    text: 'Merging a pull request leaves the branch on origin. GitHub shows a Delete branch button right after the merge, and most teams press it.',
                },
            ],
            task: 'Press Switch and pick main, then press Pull. Finish with Delete branch on chocolate.',
            done: 'Your main has the chips, and chocolate is gone from your list. Sam is already looking for an excuse to make pancakes for dinner.',
            // Check. You're on main, local history has the merge, and chocolate is gone from your branches.
            actions: [
                {
                    type: ActionType.Switch,
                    branch: 'main',
                    files: [
                        {
                            name: 'pancakes',
                            content: lines(
                                'Pancakes',
                                '1 mashed banana',
                                '1 cup flour',
                                '1 cup oat milk',
                                '1 pinch of salt',
                                '1 handful of blueberries',
                                '1 spoon of maple syrup',
                                'Serves 4',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'groceries',
                            content: lines('eggs', 'flour', 'butter', 'milk'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'cookies',
                            content: lines(
                                'Cookies',
                                '2 cups flour',
                                '1 cup butter',
                                '1 cup sugar',
                                '1 cup of chocolate chips',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'soup',
                            content: lines(
                                'Soup',
                                '3 potatoes',
                                '1 onion',
                                '4 cups of water',
                                '1 handful of croutons',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'notes',
                            content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.New,
                            staged: false,
                        },
                    ],
                },
                {
                    type: ActionType.Pull,
                    files: [
                        {
                            name: 'pancakes',
                            content: lines(
                                'Pancakes',
                                '1 mashed banana',
                                '1 cup flour',
                                '1 cup oat milk',
                                '1 pinch of salt',
                                '1 handful of blueberries',
                                '1 spoon of maple syrup',
                                '1 cup of chocolate chips',
                                'Serves 4',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'groceries',
                            content: lines('eggs', 'flour', 'butter', 'milk'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'cookies',
                            content: lines(
                                'Cookies',
                                '2 cups flour',
                                '1 cup butter',
                                '1 cup sugar',
                                '1 cup of chocolate chips',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'soup',
                            content: lines(
                                'Soup',
                                '3 potatoes',
                                '1 onion',
                                '4 cups of water',
                                '1 handful of croutons',
                            ),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.Unchanged,
                            staged: false,
                        },
                        {
                            name: 'notes',
                            content: lines('The pancakes are from a box mix.', 'Buy more box mix.'),
                            modifiedOn: '2026-10-02',
                            status: FileStatus.New,
                            staged: false,
                        },
                    ],
                },
                { type: ActionType.DeleteBranch, branch: 'chocolate' },
            ],
        },
    ],
};
